# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sua-imagem-backend:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: backend-storage
              mountPath: /app/shared
      volumes:
        - name: backend-storage
          hostPath:
            path: C:/Git/Vet/backend/shared

---
# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
