apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          image: asdkant/fastapi-hello-world
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: backend-storage
              mountPath: /app/shared
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-pvc
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000