apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  labels:
    name: backend-persist-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client