apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: frontend-storage
          mountPath: /app/shared
      volumes:
      - name: frontend-storage
      hostPath:
        path: C:/Git/Vet/frontend/shared
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000